### ISSUE TITLE
restructure

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-factory#10]
propose interspersing two directories:
scripts/box (i.e. platform)
scripts/content

and moving other scripts directories inside of them

**Comment by tim-moody** [comment]
actually maybe box and content should be parallel with docs and put apks in content and keys in box

maybe scripts doesn't add much info

**Comment by georgejhunt** [comment]
It's important to get the structure right now, and then hold on to it
thereafter.

Some scripts I've written will need to be changed, and then tested, but
this is a good time to get it right.
