### ISSUE TITLE
min-sd and cp-sd have path to opt/schoolserver/xsce, S.B. iiab

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-factory#23]

**Comment by tim-moody** [comment]
where is this supposed to go?

echo $FILENAME > ../../last-filename
echo $HASH > ../../last-hash

**Comment by holta** [comment]
Hopefully @georgejhunt can clarify!

Are these 2 "nonces" (or whatev they are!) supposed to be saved to /mnt/sdcard/opt/schoolserver/iiab or what? (:

**Comment by holta** [comment]
CLARIF that min-sd and cp-sd are here:
https://github.com/iiab/iiab-factory/tree/master/box/rpi

And are documented here:
https://github.com/iiab/iiab-factory/blob/master/box/rpi/howto-mkimg.txt
http://download.iiab.io/packages/imager/

**Comment by holta** [comment]
Appears to have been fixed around early 2018.
