### ISSUE TITLE
add status=progress to cp-sd

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-factory#24]

**Comment by georgejhunt** [comment]
My memory is that CentOS does not have a dd that includes status=progress.  But at this point I'm using a ubuntu OS for my work horse -- so I'm fine with it

**Comment by holta** [comment]
Go for it.  I don't think "status=progess" is fatal on legacy systems that don't yet support it.

**Comment by holta** [comment]
Seems this is not yet implemented 15 months later?

(Is this still needed?)
