### ISSUE TITLE
One line installer keeps on trying to update

### ISSUE THREAD

**Issue by mir123** [iiab/iiab-factory#63]
One line installer keeps on trying to update after reboot, i.e. keeps rebooting. Suspect this might have to do with localization and not catching the fact the os is updated? Or maybe because I updated using Raspbian before running one line installer.

1. Install Raspbian
2. Updated using Raspbian dialogs 
3. curl d.iiab.io/install.txt | sudo bash
4. reboot
5. sudo iiab
6. reboots again and again

OS: Raspbian
Localization: es

**Comment by holta** [comment]
Which exact Raspbian are you using, of the 3 at https://www.raspberrypi.org/downloads/raspbian/ ?

What exact hardware are you using, e.g. Raspberry Pi 3 or 3 B+?

Can you see anything in screen right before it reboots?

Can you send a photo of any error messages?

Thanks!

**Comment by holta** [comment]
@mir123 I suspect you are correct this likely has to do with Spanish localization.

For Now: also consider localizing Raspbian to English at the beginning, and then converting it to Spanish right after IIAB's core software is installed?

**Comment by mir123** [comment]
Raspbian was full version, 2018-11-13-raspbian-stretch-full.zip (Raspbian Stretch with desktop and recommended software)

I commented out lines 144 to 160 in order to continue.

i can confirm reverting to en localization fixes the issue.

**Comment by holta** [comment]
To help us fix this, can you set localization to Spanish, reboot, then run:
```
apt -qq update > /tmp/apt.stdout 2> /tmp/apt.stderr
apt -y install pastebinit
cat /tmp/apt.stdout | pastebinit
cat /tmp/apt.stderr | pastebinit
locale | pastebinit
```
Thanks @mir123 if you can!

(If so, please send us the 3 resulting paste.ubuntu.com URL's)

**Comment by mir123** [comment]
For whatever reason the first cat does not return an URL.  contents of apt.stdout:

> Se puede actualizar 1 paquete. Ejecute «apt list --upgradable» para verlo.

The other URLs:

http://paste.debian.net/1072790/
http://paste.debian.net/1072791/
